### ISSUE TITLE
rvs from Kent Distribution

### ISSUE THREAD

**Issue by hayalaso** [edfraenkel/kent_distribution#2]
After creating a KentDistribution object, what does rvs return? Are they angles or something else? It wasn't clear to me from the code. 

Thanks,
Hugo Ayala

**Comment by edfraenkel** [comment]
Hi Hugo,

It is a while ago that I wrote the code. I'll have a look at it and add
some documentation.

Best regards,

Daniel


On 9 Sep 2017 11:16 pm, "hayalaso" <notifications@github.com> wrote:

After creating a KentDistribution object, what does rvs return? Are they
angles or something else? It wasn't clear to me from the code.

Thanks,
Hugo Ayala

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/edfraenkel/kent_distribution/issues/2>, or mute the
thread

**Comment by hayalaso** [comment]
Hi Daniel, 
Thanks for the reply. I played around with it a little more. I read this document (https://arxiv.org/pdf/1506.08105.pdf) and compare some equations with your code.  After using the function rvs, I realized it was giving me the cartesian coordinates in the order z,x,y.  I did the transformation accordingly to spherical and I got what I was expecting.
